//
//  JKResponseHeader.h
//  JKSDK
//
//  Created by Sheng-Tsang Uou on 2020/7/15.
//  Copyright © 2020 Sheng-Tsang Uou. All rights reserved.
//

#import "JKMessageResponse.h"
#import "JKSendMessageResponse.h"
#import "JKScheduledMessageResponse.h"
#import "JKMessageResponse.h"
#import "JKJoinChannelResponse.h"
#import "JKCreateChannelResponse.h"
#import "JKDismissChannelResponse.h"
#import "JKLeaveChannelResponse.h"
#import "JKInviteMemberResponse.h"
#import "JKKickMemberResponse.h"
#import "JKMemberRoleResponse.h"
#import "JKChannelPreferenceResponse.h"
#import "JKChannelProfileResponse.h"
#import "JKProgressResponse.h"
#import "JKMessageProgressResponse.h"
#import "JKMarkReadResponse.h"
#import "JKMarkReadNewsResponse.h"
#import "JKDeleteMessagesResponse.h"
#import "JKDeleteChannelMessagesResponse.h"
#import "JKDeleteAllMessagesResponse.h"
#import "JKCreateVoteResponse.h"
#import "JKScheduledVoteResponse.h"
#import "JKChannelResponse.h"
#import "JKQueryChannelsResponse.h"
#import "JKQueryChannelReadInfoResponse.h"
#import "JKQueryVoteResponse.h"
#import "JKQueryChannelsReadTimeResponse.h"
#import "JKQueryUnreadChannelsResponse.h"
#import "JKQueryChannelMembersResponse.h"
#import "JKQueryVoteOptionResponse.h"
#import "JKUserDeviceNotifyPreviewResponse.h"
#import "JKUserDeviceMuteResponse.h"
#import "JKUserDeviceNotifySoundResponse.h"
#import "JKUserPushTokenResponse.h"
#import "JKQueryUserDeviceNotifyResponse.h"
#import "JKDownloadPlusMenuResponse.h"
#import "JKQueryPlusMenuListResponse.h"
#import "JKQueryMeetRoomInfoResponse.h"
#import "JKConfRoomItemResponse.h"
#import "JKCreateMeetRoomResponse.h"
#import "JKCheckMeetPasswordResponse.h"
#import "JKSetMeetSignalResponse.h"
#import "JKSetChannelMemberProfileResponse.h"
#import "JKQueryMessageReadCountResponse.h"
#import "JKQueryMessageReadUsersResponse.h"
#import "JKSetUserProfileResponse.h"
#import "JKQueryUserDataResponse.h"
#import "JKQueryUserProfileResponse.h"
#import "JKQueryMessageResponse.h"
#import "JKMessageAttrResponse.h"
#import "JKRecallResponse.h"
#import "JKNewsMessageResponse.h"
#import "JKCreateNewsChannelResponse.h"
#import "JKModifyUserProfileResponse.h"
#import "JKMeetSignalResponse.h"
#import "JKScheduledInDueTimeMessageResponse.h"
#import "JKCastVoteResponse.h"
#import "JKCapabilityResponse.h"
